version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Enseroot"
      LDAP_DOMAIN: "enseroot.com"
      LDAP_BASE_DN: "dc=enseroot,dc=com"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CONFIG_PASSWORD: "config123"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    networks:
      - ldap_network

volumes:
  openldap_data:
  openldap_config:

networks:
  ldap_network:
    driver: bridge